re-enable tests with packit 0.20
even though we are doing -Xtheirs, git still can fail resolving conflicts
which is really weird; in such a case, let's just `add .` and continue
the cherry-pick process

example:
  git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
    cmdline: git cherry-pick --keep-redundant-commits --strategy=recursive --strategy-option=theirs updates~1
    stderr: 'error: could not apply 92f8332... podman-2.1.1 base
  hint: after resolving the conflicts, mark the corrected paths
  hint: with 'git add <paths>' or 'git rm <paths>'
  hint: and commit the result with 'git commit''

in this case, git couldn't resolve conflicts in two files

Signed-off-by: Tomas Tomecek <ttomecek@redhat.com>